### ISSUE TITLE
adding molularity to our design

### ISSUE THREAD

**Issue by ziyad00** [petroly-initiative/petroly-django#55]

**Comment by Muhab2001** [comment]
I believe the project design is fairly modular thanks to Django's logic separation via apps and @ammar-faifi amazing efforts in maintaining it. I believe that the project in its current state is fairly maintainable and scalable. But I Believe our `strawberry` setup lacks documentation

**Comment by ammar-faifi** [comment]
believe me I did not know what @ziyad00  is meaning
