### ISSUE TITLE
Docker integration to this repo

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-django#59]
We are all fascinating about how Docker images can ease the development and have the same environment for all. 

for those reasons we start working on creating a `Dockerfile` file

**Comment by KSAm3lm** [comment]
Great project. Any updates on the Dockerization plan?

**Comment by ammar-faifi** [comment]
@KSAm3lm  The idea was to integrate to docker hosting services, to lower the cost, and it seems very plausible.
I just stopped at the point of integrating a `PostgreSQL`.

not sure if i'll have time to it, but your contribution is welcome.

**Comment by ammar-faifi** [comment]
just noticed i deleted this issue's repo 2 days ago, 
i had in mind starting it from beginning is better. Sorry for that

**Comment by ammar-faifi** [comment]
https://github.com/petroly-initiative/petroly-django/tree/flyio fixes #59
