### ISSUE TITLE
Forgot password Issue

### ISSUE THREAD

**Issue by nrbnlulu** [petroly-initiative/petroly-django#79]
Forgot password form claims to send me a mail even though I am not registered , I think it should show some error message.

**Comment by ammar-faifi** [comment]
the problem is with `send_password_reset_email` mutation does not recognize whether the the email exits or not.

as in 

https://github.com/nrbnlulu/strawberry-django-auth/blob/8da8fd6265b82c031e4c5416803477359239691f/gqlauth/user/resolvers.py#L254-L265

**Comment by nrbnlulu** [comment]
Oh we should open an issue about that..
I am currently working on async support so maybe later.

**Comment by ammar-faifi** [comment]
I'll see if I can improve it 👍
